from django.conf import settings

HTTPS_IFRAME_COOKIESETTER_URL_TO_CHECK = getattr(settings, 'COOKIESETTER_URL_TO_CHECK', '/myview')
HTTPS_IFRAME_COOKIESETTER_BROWSERS = getattr(settings, 'COOKIESETTER_BROWSERS', ['Safari','Mobile Safari'])
HTTPS_IFRAME_COOKIESETTER_ADDITIONAL_CHECKS = getattr(settings, 'COOKIESETTER_ADDITIONAL_CHECKS', None)
HTTPS_IFRAME_COOKIESETTER_ONLY_HTTPS = getattr(settings, 'COOKIESETTER_ONLY_HTTPS', True)
HTTPS_IFRAME_COOKIESETTER_LOADING_GRAPHIC = getattr(settings, 'COOKIESETTER_LOADING_GRAPHIC', 'http://loadinggif.com/images/image-selection/35.gif')